---
- hosts: localhost
  tasks:
      - name: Require ansible version >=2.5
        assert:
          that: 
            - "{{ ansible_version is defined }}"
            - "{{ ansible_version.full is version(2.5,'>=') }}"

- hosts: slaves
  become: yes
  roles:
      - node
      - ssh

- hosts: master
  become: yes
  roles:
      - node
      - ssh_server
      - master

- hosts: slaves
  become: yes
  roles:
      - slave

