---
- name: "update apt cache"
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: "install xroad-confproxy via apt"
  apt:
    name: xroad-confproxy
    state: latest
    force: yes
  when: ansible_os_family == "Debian"
