---
- name: Install required packages
  apt:
    name: "{{ items }}"
    state: present
    update_cache: yes
  vars:
    items:
      - acl
      - curl
      - apt-transport-https
      - locales
      - aptitude
      - software-properties-common

- name: System details
  debug:
    msg: "{{ ansible_distribution_version }}"
  tags:
    - debug

- name: Clean local repo
  file:
    path: "/xroad/"
    state: absent
  tags:
    - clean-local-repo

- name: Copy {{ ansible_distribution_release }} DEB packages (Ubuntu)
  become: yes
  copy: src="../src/packages/build/ubuntu{{ ansible_distribution_version }}/" dest="/xroad/"

- name: Add empty Packages to local repo for apt to run
  file:
    path: "/xroad/Packages"
    state: touch
  tags:
    - clean-local-repo

- name: Ensure dpkg-dev
  become: yes
  apt: name=dpkg-dev state=present update_cache=yes

- name: Scan new packages
  become: yes
  shell: "dpkg-scanpackages -m . >Packages"
  args:
    chdir: /xroad

- name: Disable automatic upgrades
  copy:
    src: 99override-auto
    dest: /etc/apt/apt.conf.d/
    owner: root
    group: root
  when: (disable_automatic_upgrades is defined) and (disable_automatic_upgrades)

- name: Install X-Road apt repo key
  apt_key:
    url: "{{ubuntu_apt_key}}"
    state: present
  when: package_source == "remote" and (ansible_distribution == "Ubuntu")

- name: Remove old repo config
  file:
    path: /etc/apt/sources.list.d/xroad.list
    state: absent

- name: xroad apt repository
  apt_repository:
    repo: "{{ubuntu_apt_repo}}"
    state: present
    filename: xroad
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: enable UTF-8 locales
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ (['en_US.UTF-8'] + extra_locales | default([])) | unique }}"
